apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: ticket-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: nginx
        image: shinojl4dx/frontend:fb1216a
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: ticket-system
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80        # cluster port
      targetPort: 80  # container port
      nodePort: 30080 # p
